Function Get-HyperVLANDrivers(){
$HyperVLANDriver1 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\ndiscap.inf")
$HyperVLANDriver2 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\ndisimplatform.inf")
$HyperVLANDriver3 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\ndisimplatformmp.inf")
$HyperVLANDriver4 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\ndisuio.inf")
$HyperVLANDriver5 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\ndisvirtualbus.inf")
$HyperVLANDriver6 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\net1ic64.inf")
$HyperVLANDriver7 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\net1yx64.inf")
$HyperVLANDriver8 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\net44amd.inf")
$HyperVLANDriver9 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\net819xp.inf")
$HyperVLANDriver10 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\net8185.inf")
$HyperVLANDriver11 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\net8187bv64.inf")
$HyperVLANDriver12 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\net8187se64.inf")
$HyperVLANDriver13 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\net8192se64.inf")
$HyperVLANDriver14 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\net8192su64.inf")
$HyperVLANDriver15 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netathrx.inf")
$HyperVLANDriver16 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netavpna.inf")
$HyperVLANDriver17 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netavpnt.inf")
$HyperVLANDriver18 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netax8179_178a.inf")
$HyperVLANDriver19 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netax88772.inf")
$HyperVLANDriver20 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netb57va.inf")
$HyperVLANDriver21 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netbc63a.inf")
$HyperVLANDriver22 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netbc64.inf")
$HyperVLANDriver23 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netbrdg.inf")
$HyperVLANDriver24 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netbvbda.inf")
$HyperVLANDriver25 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netbxnda.inf")
$HyperVLANDriver26 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\nete1e3e.inf")
$HyperVLANDriver27 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\nete1g3e.inf")
$HyperVLANDriver28 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\neteFE3e.inf")
$HyperVLANDriver29 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netelx.inf")
$HyperVLANDriver30 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netevbda.inf")
$HyperVLANDriver31 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netg664.inf")
$HyperVLANDriver32 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netimrn.inf")
$HyperVLANDriver33 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netip6.inf")
$HyperVLANDriver34 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netirda.inf")
$HyperVLANDriver35 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netjme.inf")
$HyperVLANDriver36 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netk57a.inf")
$HyperVLANDriver37 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\net1c63x64.inf")
$HyperVLANDriver38 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\net1e64.inf")
$HyperVLANDriver39 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\net160a.inf")
$HyperVLANDriver40 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\net260a.inf")
$HyperVLANDriver41 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netldp.inf")
$HyperVLANDriver42 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netloop.inf")
$HyperVLANDriver43 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netmscli.inf")
$HyperVLANDriver44 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netmyk64.inf")
$HyperVLANDriver45 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netnb.inf")
$HyperVLANDriver46 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netnvm64.inf")
$HyperVLANDriver47 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netnvma.inf")
$HyperVLANDriver48 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netnwifi.inf")
$HyperVLANDriver49 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netpacer.inf")
$HyperVLANDriver50 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netpgm.inf")
$HyperVLANDriver51 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netr28ux.inf")
$HyperVLANDriver52 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netr28x.inf")
$HyperVLANDriver53 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netr7364.inf")
$HyperVLANDriver54 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netrasa.inf")
$HyperVLANDriver55 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netrass.inf")
$HyperVLANDriver56 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netrast.inf")
$HyperVLANDriver57 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netrndis.inf")
$HyperVLANDriver58 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netrt630x64.inf")
$HyperVLANDriver59 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netrtl64.inf")
$HyperVLANDriver60 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netrtwlane.inf")
$HyperVLANDriver61 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netrtwlanu.inf")
$HyperVLANDriver62 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netserv.inf")
$HyperVLANDriver63 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netsstpa.inf")
$HyperVLANDriver64 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netsstpt.inf")
$HyperVLANDriver65 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\nettcpip.inf")
$HyperVLANDriver66 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\nettun.inf")
$HyperVLANDriver67 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netv1x64.inf")
$HyperVLANDriver68 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netvchannel.inf")
$HyperVLANDriver69 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netvf63a.inf")
$HyperVLANDriver70 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netvfx64.inf")
$HyperVLANDriver71 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netg664.inf")
$HyperVLANDriver72 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netvg63a.inf")
$HyperVLANDriver73 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netvwifibus.inf")
$HyperVLANDriver74 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netvwififlt.inf")
$HyperVLANDriver75 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netvwifimp.inf")
$HyperVLANDriver76 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netvwwanmp.inf")
$HyperVLANDriver77 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netvxx64.inf")
$HyperVLANDriver78 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netwew00.inf")
$HyperVLANDriver79 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netwew02.inf")
$HyperVLANDriver80 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netwlan92de.inf")
$HyperVLANDriver81 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netwlv64.inf")
$HyperVLANDriver82 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netwmbclass.inf")
$HyperVLANDriver83 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netwns64.inf")
$HyperVLANDriver84 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netwsw00.inf")
$HyperVLANDriver85 = (Test-Path -Path "C:\OSDCloud\Drivers\Virtualization\HyperV\Network\netxex64.inf")

If(($HyperVLANDriver1 -eq $true) -and ($HyperVLANDriver2 -eq $true) -and ($HyperVLANDriver3 -eq $true) -and ($HyperVLANDriver4 -eq $true) -and ($HyperVLANDriver5 -eq $true) -and ($HyperVLANDriver6 -eq $true) -and ($HyperVLANDriver7 -eq $true) -and ($HyperVLANDriver8 -eq $true) -and ($HyperVLANDriver9 -eq $true) -and ($HyperVLANDriver10 -eq $true) -and ($HyperVLANDriver11 -eq $true) -and ($HyperVLANDriver12 -eq $true) -and ($HyperVLANDriver13 -eq $true) -and ($HyperVLANDriver14 -eq $true) -and ($HyperVLANDriver15 -eq $true) -and ($HyperVLANDriver16 -eq $true) -and ($HyperVLANDriver17 -eq $true) -and ($HyperVLANDriver18 -eq $true) -and ($HyperVLANDriver19 -eq $true) -and ($HyperVLANDriver20 -eq $true) -and ($HyperVLANDriver21 -eq $true) -and ($HyperVLANDriver22 -eq $true) -and ($HyperVLANDriver23 -eq $true) -and ($HyperVLANDriver24 -eq $true) -and ($HyperVLANDriver25 -eq $true) -and ($HyperVLANDriver26 -eq $true) -and ($HyperVLANDriver27 -eq $true) -and ($HyperVLANDriver28 -eq $true) -and ($HyperVLANDriver29 -eq $true) -and ($HyperVLANDriver30 -eq $true) -and ($HyperVLANDriver31 -eq $true) -and ($HyperVLANDriver32 -eq $true) -and ($HyperVLANDriver33 -eq $true) -and ($HyperVLANDriver34 -eq $true) -and ($HyperVLANDriver35 -eq $true) -and ($HyperVLANDriver36 -eq $true) -and ($HyperVLANDriver37 -eq $true) -and ($HyperVLANDriver38 -eq $true) -and ($HyperVLANDriver39 -eq $true) -and ($HyperVLANDriver40 -eq $true) -and ($HyperVLANDriver41 -eq $true) -and ($HyperVLANDriver42 -eq $true) -and ($HyperVLANDriver43 -eq $true) -and ($HyperVLANDriver44 -eq $true) -and ($HyperVLANDriver45 -eq $true) -and ($HyperVLANDriver46 -eq $true) -and ($HyperVLANDriver47 -eq $true) -and ($HyperVLANDriver48 -eq $true) -and ($HyperVLANDriver49 -eq $true) -and ($HyperVLANDriver50 -eq $true) -and ($HyperVLANDriver51 -eq $true) -and ($HyperVLANDriver52 -eq $true) -and ($HyperVLANDriver53 -eq $true) -and ($HyperVLANDriver54 -eq $true) -and ($HyperVLANDriver55 -eq $true) -and ($HyperVLANDriver56 -eq $true) -and ($HyperVLANDriver57 -eq $true) -and ($HyperVLANDriver58 -eq $true) -and ($HyperVLANDriver59 -eq $true) -and ($HyperVLANDriver60 -eq $true) -and ($HyperVLANDriver61 -eq $true) -and ($HyperVLANDriver62 -eq $true) -and ($HyperVLANDriver63 -eq $true) -and ($HyperVLANDriver64 -eq $true) -and ($HyperVLANDriver65 -eq $true) -and ($HyperVLANDriver66 -eq $true) -and ($HyperVLANDriver67 -eq $true) -and ($HyperVLANDriver68 -eq $true) -and ($HyperVLANDriver69 -eq $true) -and ($HyperVLANDriver70 -eq $true) -and ($HyperVLANDriver71 -eq $true) -and ($HyperVLANDriver72 -eq $true) -and ($HyperVLANDriver73 -eq $true) -and ($HyperVLANDriver74 -eq $true) -and ($HyperVLANDriver75 -eq $true) -and ($HyperVLANDriver76 -eq $true) -and ($HyperVLANDriver77 -eq $true) -and ($HyperVLANDriver78 -eq $true) -and ($HyperVLANDriver79 -eq $true) -and ($HyperVLANDriver80 -eq $true) -and ($HyperVLANDriver81 -eq $true) -and ($HyperVLANDriver82 -eq $true) -and ($HyperVLANDriver83 -eq $true) -and ($HyperVLANDriver84 -eq $true) -and ($HyperVLANDriver85 -eq $true)){
Write-Verbose "Hyper-V Network drivers have been downloaded and extracted" -Verbose
}
ElseIf(($HyperVLANDriver1 -eq $false) -and ($HyperVLANDriver2 -eq $false) -and ($HyperVLANDriver3 -eq $false) -and ($HyperVLANDriver4 -eq $false) -and ($HyperVLANDriver5 -eq $false) -and ($HyperVLANDriver6 -eq $false) -and ($HyperVLANDriver7 -eq $false) -and ($HyperVLANDriver8 -eq $false) -and ($HyperVLANDriver9 -eq $false) -and ($HyperVLANDriver10 -eq $false) -and ($HyperVLANDriver11 -eq $false) -and ($HyperVLANDriver12 -eq $false) -and ($HyperVLANDriver13 -eq $false) -and ($HyperVLANDriver14 -eq $false) -and ($HyperVLANDriver15 -eq $false) -and ($HyperVLANDriver16 -eq $false) -and ($HyperVLANDriver17 -eq $false) -and ($HyperVLANDriver18 -eq $false) -and ($HyperVLANDriver19 -eq $false) -and ($HyperVLANDriver20 -eq $false) -and ($HyperVLANDriver21 -eq $false) -and ($HyperVLANDriver22 -eq $false) -and ($HyperVLANDriver23 -eq $false) -and ($HyperVLANDriver24 -eq $false) -and ($HyperVLANDriver25 -eq $false) -and ($HyperVLANDriver26 -eq $false) -and ($HyperVLANDriver27 -eq $false) -and ($HyperVLANDriver28 -eq $false) -and ($HyperVLANDriver29 -eq $false) -and ($HyperVLANDriver30 -eq $false) -and ($HyperVLANDriver31 -eq $false) -and ($HyperVLANDriver32 -eq $false) -and ($HyperVLANDriver33 -eq $false) -and ($HyperVLANDriver34 -eq $false) -and ($HyperVLANDriver35 -eq $false) -and ($HyperVLANDriver36 -eq $false) -and ($HyperVLANDriver37 -eq $false) -and ($HyperVLANDriver38 -eq $false) -and ($HyperVLANDriver39 -eq $false) -and ($HyperVLANDriver40 -eq $false) -and ($HyperVLANDriver41 -eq $false) -and ($HyperVLANDriver42 -eq $false) -and ($HyperVLANDriver43 -eq $false) -and ($HyperVLANDriver44 -eq $false) -and ($HyperVLANDriver45 -eq $false) -and ($HyperVLANDriver46 -eq $false) -and ($HyperVLANDriver47 -eq $false) -and ($HyperVLANDriver48 -eq $false) -and ($HyperVLANDriver49 -eq $false) -and ($HyperVLANDriver50 -eq $false) -and ($HyperVLANDriver51 -eq $false) -and ($HyperVLANDriver52 -eq $false) -and ($HyperVLANDriver53 -eq $false) -and ($HyperVLANDriver54 -eq $false) -and ($HyperVLANDriver55 -eq $false) -and ($HyperVLANDriver56 -eq $false) -and ($HyperVLANDriver57 -eq $false) -and ($HyperVLANDriver58 -eq $false) -and ($HyperVLANDriver59 -eq $false) -and ($HyperVLANDriver60 -eq $false) -and ($HyperVLANDriver61 -eq $false) -and ($HyperVLANDriver62 -eq $false) -and ($HyperVLANDriver63 -eq $false) -and ($HyperVLANDriver64 -eq $false) -and ($HyperVLANDriver65 -eq $false) -and ($HyperVLANDriver66 -eq $false) -and ($HyperVLANDriver67 -eq $false) -and ($HyperVLANDriver68 -eq $false) -and ($HyperVLANDriver69 -eq $false) -and ($HyperVLANDriver70 -eq $false) -and ($HyperVLANDriver71 -eq $false) -and ($HyperVLANDriver72 -eq $false) -and ($HyperVLANDriver73 -eq $false) -and ($HyperVLANDriver74 -eq $false) -and ($HyperVLANDriver75 -eq $false) -and ($HyperVLANDriver76 -eq $false) -and ($HyperVLANDriver77 -eq $false) -and ($HyperVLANDriver78 -eq $false) -and ($HyperVLANDriver79 -eq $false) -and ($HyperVLANDriver80 -eq $false) -and ($HyperVLANDriver81 -eq $false) -and ($HyperVLANDriver82 -eq $false) -and ($HyperVLANDriver83 -eq $false) -and ($HyperVLANDriver84 -eq $false) -and ($HyperVLANDriver85 -eq $false)){
$HyperVLANDrivers = Invoke-WebRequest("")
Invoke-Expression $($HyperVLANDrivers.Content)
}
}

